language: cpp
matrix:
    include:
        - os: linux
          sudo: required
          dist: trusty
          install:
            - ./setup
        - os: osx
          install:
            - ./setup
script:
  - cd ./firmware/HelloWorld/
  - source env.sh
  - make build
  - ls ./build/binaries/firmware.elf
  - ls ./build/binaries/firmware.hex
  - ls ./build/binaries/firmware.lst
  - ls ./build/binaries/firmware.map
  - make test
