language: generic
matrix:
    include:
        - os: linux
          sudo: required
          dist: bionic
          before_install:
            - sudo apt-get -y install doxygen graphviz
            - pip install --user cpp-coveralls
            - sudo apt install -y nodejs nodejs-dev node-gyp libssl1.0-dev
            - sudo apt install -y npm
            - sudo npm install -g cspell@4.0.38
          script:
            - cd projects/continuous_integration/
            - make quick-presubmit
            - make spellcheck
            - make doxygen
            # TODO(#1289): Add this back
            # - make find-missing-tests
            # TODO(#1290): Add this back
            # - make find-unused-tests
          after_success:
            - cd ../../
            - coveralls --gcov "gcov-8"
              --include "library/L0_Platform"
              --include "library/L1_Peripheral"
              --include "library/L2_HAL"
              --include "library/L3_Application"
              --include "library/utility"
          deploy:
            provider: pages
            skip-cleanup: true
            github-token: $GITHUB_TOKEN
            keep-history: true
            on:
              branch: master
        - os: osx
          osx_image: xcode10
          script:
            - cd projects/continuous_integration/
            - make quick-presubmit
        - os: osx
          osx_image: xcode11.3
          script:
            - cd projects/continuous_integration/
            - make quick-presubmit
install: ./setup

