language: generic
matrix:
    include:
        - os: linux
          sudo: required
          dist: xenial
          after_success:
            - cd ../../
            - coveralls --gcov "$(pwd)/tools/clang+llvm-7.0.0-x86_64-linux-gnu-ubuntu-16.04/bin/llvm-cov gcov"
              --include "library/L0_Platform"
              --include "library/L1_Peripheral"
              --include "library/Utility"
              --include "library/L2_HAL"
              --include "library/L3_Application"
            - sudo apt-get -y install doxygen graphviz
            - cd api/
            - doxygen sjsu-dev2-doxygen.conf
          deploy:
            provider: pages
            skip-cleanup: true
            github-token: $GITHUB_TOKEN
            keep-history: true
            on:
              branch: master
        - os: osx
          osx_image: xcode10
before_install: pip install --user cpp-coveralls
install: ./setup
script:
  - cd projects/hello_world/
  - make presubmit
