language: cpp
matrix:
    include:
        - os: linux
          sudo: required
          dist: trusty
          before_install:
            - pip install --user cpp-coveralls
          install:
            - ./setup
          script:
            - cd ./firmware/HelloWorld/
            - source env.sh
            - make presubmit
          after_success:
            - cd ../../
            - coveralls -i firmware/library/ -i firmware/HelloWorld/build/test/compiled/ -e tools/ -e firmware/library/third_party/ --gcov $(which gcov-7) --gcov-options '\-lp'
        - os: osx
          osx_image: xcode7
          before_install:
            - brew update
            - brew cask uninstall oclint
            - brew install gcc@7 || echo "proceed"
          install:
            - ./setup
          script:
            - cd ./firmware/HelloWorld/
            - source env.sh
            - make presubmit HOST_CPPC=g++-7 HOST_CC=gcc-7
          after_success:
            - cd ../../
            - brew update
            - brew install pyenv
            - eval "$(pyenv init -)"
            - pyenv install 2.7.6
            - pyenv global 2.7.6
            - pyenv rehash
            - pip install cpp-coveralls
            - pyenv rehash
            - ./configure --enable-gcov && make && make check
            - coveralls -i firmware/library/ -i firmware/HelloWorld/build/test/compiled/ -e tools/ -e firmware/library/third_party/ --gcov $(which gcov-7) --gcov-options '\-lp'
