# Project Information
site_name: SJSU-DEV2
# Configuration
theme:
  name: 'material'
  # custom_dir: css/
  # include_sidebar: true
  highlightjs: true
  hljs_style:
    - monokai
  extra_css:
    - 'stylesheets/extra.css'

docs_dir: documentation/

# Copyright
copyright: 'Copyright (C) 2018-2019 San Jose State University Computer Engineering Department'

#Navigation
nav:
  - Home: 'index.md'
  - Get Started:
    - Getting started: 'getting-started/getting-started.md'
    - How to Use Make: 'getting-started/using-make.md'
  - Guides:
    - Understanding the Library Directory Structure:
      - 'guides/directory_layout/project.md'
      - 'guides/directory_layout/demos.md'
      - 'guides/directory_layout/library.md'
      - 'guides/directory_layout/reference.md'
    - 'guides/firmware_debugging.md'
    - 'guides/unit_testing.md'
    - 'guides/multi_platform.md'
  - Contributing:
    - 'contributing/philosophy.md'
    - 'contributing/levels.md'
    - 'contributing/level_guide/L0_platform.md'
    - 'contributing/level_guide/L1_peripheral.md'
    - 'contributing/level_guide/L2_hal.md'
    - 'contributing/level_guide/L3_application.md'
    - 'contributing/presubmit-checks.md'
    - 'contributing/style.md'
    - 'contributing/techniques/left-to-right.md'
  - 'about.md'
  - 'copyrights.md'

markdown_extensions:
  - admonition
  - pymdownx.mark # highlighting
  - pymdownx.superfences # nest code
  - codehilite # code syntax coding
  - toc:
      permalink:
