# Run this workflow every time a new commit pushed to your repository
on: [pull_request]

jobs:
  linux_presubmit:
    name: Linux Presubmit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Cpp Coveralls
        run: pip install --user cpp-coveralls

      - name: Install Doxygen and Graphviz
        run: sudo apt-get -y install doxygen graphviz

      - name: Install cspell
        run: sudo npm install -g cspell@4.0.38

      - name: Run Installer
        run: ./setup

      - name: Run Presubmit
        working-directory: projects/continuous_integration
        run: make presubmit

      - name: Run Code Coverage
        working-directory: projects/continuous_integration
        run: make coverage

      - name: Run Code Spellcheck
        working-directory: projects/continuous_integration
        run: make spellcheck

      - name: Run Doxygen
        working-directory: projects/continuous_integration
        run: make doxygen

  macosx_presubmit:
    name: MacOSX Presubmit
    runs-on: macos-10.15
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Installer
        run: ./setup

      - name: Run Presubmit
        working-directory: projects/continuous_integration
        run: make presubmit
